<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    <LangVersion>latest</LangVersion>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <DefineConstants>$(DefineConstants);SPT_4_0;STEAMAUDIO_ENABLED</DefineConstants>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- <AllowUnsafeBlocks>true</AllowUnsafeBlocks> -->

    <Product>Lambda</Product>
    <Version>0.7.48</Version>
    <Description>Made by ifp and tarkin</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="Microsoft.Unity.Analyzers" Version="1.23.0" PrivateAssets="all" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.43" IncludeAssets="compile" />
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>0649,0169,0414,NU1702</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".\Configuration\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include=".\.Binaries*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <!-- BepInEx / SPT -->
    <Reference Include="$(BepInExPath)\core\0Harmony.dll" />
    <Reference Include="$(BepInExPath)\core\BepInEx.dll" />
    <Reference Include="$(BepInExPath)\plugins\spt\spt-reflection.dll" />
    <Reference Include="$(BepInExPath)\plugins\Fika\Fika.Core.dll" />

    <!-- EFT -->
    <Reference Include="$(ManagedPath)\ItemComponent.Types.dll" />
    <Reference Include="$(ManagedPath)\ItemTemplate.Types.dll" />
    <Reference Include="$(ManagedPath)\Assembly-CSharp.dll" />
    <Reference Include="$(ManagedPath)\bsg.console.core.dll" />
    <Reference Include="$(ManagedPath)\Comfort.Unity.dll" />
    <Reference Include="$(ManagedPath)\Comfort.dll" />
    <Reference Include="$(ManagedPath)\Newtonsoft.Json.dll" />
    <Reference Include="$(ManagedPath)\Sirenix.Serialization.dll" />
    <Reference Include="$(ManagedPath)\UnityEngine.AudioModule.dll" />
    <Reference Include="$(ManagedPath)\UnityEngine.UI.dll" />
    <Reference Include="$(ManagedPath)\Unity.TextMeshPro.dll" />
    <Reference Include="$(ManagedPath)\Meta.XR.Audio.dll" />
    <Reference Include="$(ManagedPath)\DissonanceVoip.dll" />
    <Reference Include="$(ManagedPath)\Unity.Postprocessing.Runtime.dll" />
    <Reference Include="$(ManagedPath)\DOTween.dll" />
    <Reference Include="$(ManagedPath)\DOTween.Modules.dll" />
    <Reference Include="$(ManagedPath)\AnimationSystem.Types.dll" />


    <Reference Include="..\.Binaries\*.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lambda.UI\Lambda.UI.csproj" />

    <ProjectReference Include="..\Lambda.Shared\Lambda.Shared.csproj" />

    <ProjectReference Include="..\PacketWarden\PacketWarden.csproj" />
    
    <!-- <ProjectReference Include="..\Lambda.Audio\Lambda.Audio.SteamIntegration\Lambda.Audio.SteamIntegration.csproj" /> -->
  </ItemGroup>

  <Target Name="CopyFilesAfterBuild" AfterTargets="Build">


    <ItemGroup>
      <Binaries Include="$(OutputPath)\Unitask.dll" />
      <Binaries Include="$(OutputPath)\Unitask.*.dll" />
      <Binaries Include="./.Binaries/libraries/ScriptEngine.dll" />

      <FilesToCopyToScripts Include="$(OutputPath)\$(MSBuildProjectName).dll" />
      <FilesToCopyToScripts Include="$(OutputPath)\$(MSBuildProjectName).pdb" />

      <Configs Include="../Configuration/*.cfg" />
      <Presets Include="../Configuration/Presets/WeaponBuilds/*.json" />
      <JSON Include="../Configuration/*.jsonc" />
    </ItemGroup>


    <Copy SourceFiles="@(Binaries)" DestinationFolder="$(SPTPath)\BepInEx\plugins\ifp\Binaries" SkipUnchangedFiles="true" ContinueOnError="WarnAndContinue" />

    <Copy SourceFiles="@(Configs)" DestinationFolder="$(SPTPath)\BepInEx\config\" />
    <Copy SourceFiles="@(JSON)" DestinationFolder="$(SPTPath)\BepInEx\plugins\ifp\Configuration\" />

    <Copy SourceFiles="@(Presets)" DestinationFolder="$(SPTPath)\BepInEx\plugins\ifp\Configuration\Presets\WeaponBuilds\" SkipUnchangedFiles="true" ContinueOnError="WarnAndContinue" />

    <Copy SourceFiles="@(FilesToCopyToScripts)" DestinationFolder="$(SPTPath)\BepInEx\scripts\ifp" />
  </Target>
</Project>